[workspace]
members = [
    "src/build/host",
    "src/build/receiver",
    "src/tools/paa2png",
    "src/build/common",
    "src/build/compiler",
    "src/build/publisher",
    "src/esm",
    "src/updater/lib",
    "src/updater/extension",
    "src/updater/cli",
]
default-members = ["src/esm"]
resolver = "2"
